export const mexicoStates = [
  { id: 'MX-AGU', name: 'Aguascalientes' },
  { id: 'MX-BC', name: 'Baja California' },
  { id: 'MX-BCS', name: 'Baja California Sur' },
  { id: 'MX-CAM', name: 'Campeche' },
  { id: 'MX-COA', name: 'Coahuila' },
  { id: 'MX-COL', name: 'Colima' },
  { id: 'MX-CHH', name: 'Chihuahua' },
  { id: 'MX-CHP', name: 'Chiapas' },
  { id: 'MX-DIF', name: 'Ciudad de México' },
  { id: 'MX-DUR', name: 'Durango' },
  { id: 'MX-GRO', name: 'Guerrero' },
  { id: 'MX-GUA', name: 'Guanajuato' },
  { id: 'MX-HID', name: 'Hidalgo' },
  { id: 'MX-JAL', name: 'Jalisco' },
  { id: 'MX-MEX', name: 'México' },
  { id: 'MX-MIC', name: 'Michoacán' },
  { id: 'MX-MOR', name: 'Morelos' },
  { id: 'MX-NAY', name: 'Nayarit' },
  { id: 'MX-NL', name: 'Nuevo León' },
  { id: 'MX-OAX', name: 'Oaxaca' },
  { id: 'MX-PUE', name: 'Puebla' },
  { id: 'MX-QUE', name: 'Querétaro' },
  { id: 'MX-ROO', name: 'Quintana Roo' }, // <--- ¡Corregido!
  { id: 'MX-SLP', name: 'San Luis Potosí' },
  { id: 'MX-SIN', name: 'Sinaloa' },
  { id: 'MX-SON', name: 'Sonora' },
  { id: 'MX-TAB', name: 'Tabasco' },
  { id: 'MX-TAM', name: 'Tamaulipas' },
  { id: 'MX-TLA', name: 'Tlaxcala' },
  { id: 'MX-VER', name: 'Veracruz' },
  { id: 'MX-YUC', name: 'Yucatán' },
  { id: 'MX-ZAC', name: 'Zacatecas' },
];